### ISSUE TITLE
Contributor/community member pages

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#4] opened 2014-02-10 10:23 UTC
We want to have a rich contributor and community member profile pages, allowing to show the personal stats based on several sources (GitHub, StackOverflow, etc).

~~**UPDATE**: Initial work done with hero image. It is needed some love though.~~

**Comment by sneridagh** [comment] 2015-04-29 15:27
We decided not to have a hero photo.

**Comment by polyester** [comment] 2015-05-11 20:14
duplicate of https://github.com/plone/ploneorg.core/issues/21

**Closed** 2015-05-11 20:13 UTC
Labels: Contributor profile
